name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]



jobs:
  build:
   runs-on: ubuntu-latest

   strategy:
      matrix:
        node-version: [18.11.0]
      
   steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
  
      - name: create env file
        run: |
          touch .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_REGION=${{secrets.AWS_REGION}}" >> .env

          cat .env

      - name: build client files
        working-directory: ./
        run: |
          npm install --frozen-lockfile


      - name: zip distributions
        run: zip -r ./test.zip *

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./test.zip s3://univting-test-version1/public/

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name univting-aws-test-codedeploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name GROUP
          --s3-location bucket=univting-test-version1,bundleType=zip,key=public/test.zip
