name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]



jobs:
  build:
   runs-on: ubuntu-latest

   strategy:
      matrix:
        node-version: [18.x]
      
   steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1

      # - name: build npm_moudle #초기 실행시에만 주석 해제
      #   working-directory: ./
      #   run: |
      #     npm install
  
      - name: create env file
        run: |
          touch .env
          cat << EOF >> .env
          ${{ secrets.ENV }}

      - name: create db config file
        run : |
          mkdir config
          cd config
          touch config.json
          cat << EOF >> config.json
          ${{ secrets.config }} 

      - name: zip distributions
        run: zip -qq -r test.zip .

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./test.zip s3://univting-test-version1/public/

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name univting-aws-test-codedeploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name deploy-group
          --s3-location bucket=univting-test-version1,bundleType=zip,key=public/test.zip
